### ISSUE TITLE
route with regex fails with 404 

### ISSUE THREAD

**Issue by tablecell** [pete/watts#6]
app.rb
```RUBY
require 'watts'

class Simple < Watts::App
	class EZResource < Watts::Resource   #  Resource
		get { "Hello <hr/ > " }
	end

	resource( ['foo',/^[0-9+]$/ ], EZResource)
end

```
visit  http://localhost:9292/foo/33   got  404

**Comment by pete** [comment]
That is because the regex doesn't match `33`; the `+` is probably intended to be outside the brackets.  This one will match `/foo/3` and `/foo/+`, but not `/foo/33`.  If you correct the regex, it'll work:  `/^[0-9]+$/`.

**Comment by pete** [comment]
Well, I say it'll work, but you will still need to add an argument to the `get` block, since symbols and regexes cause Watts to call the block with arguments representing the values.  So for your example, it would pass "33":

```
class Simple < Watts::App
	class EZResource < Watts::Resource   #  Resource
		get { |match| "Hello #{match.inspect}" }
	end
	resource( ['foo',/^[0-9]+$/ ], EZResource)
end
```

You can see a more complex example in doc/examples/matching.ru.

**Comment by tablecell** [comment]
thinks  a lot for the explanation.
by the way , the default response content-type is text/plain  
app.rb 
```RB
require 'watts'

class Simple < Watts::App
	class EZResource < Watts::Resource
	 # response.headers['Content_type']="text/html"
	  
		get { "Hello, <h1>Watts!</h1>\n" }
	end

	resource('/', EZResource)
end

app = Simple.new
builder = Rack::Builder.new { run app }
run builder
```
curl -v http://localhost:9292
got 'Content-Type: text/plain'
i checked the example directory ,try use   'Watts::HTMLViewResource'  replace  'Watts::Resource' ,but still did not work

**Comment by pete** [comment]
> thanks a lot for the explanation.

Ha, any time.  I'm trying to be somewhat more active recently.

>  got 'Content-Type: text/plain'

Ah, the issue there is mixing types.  If the method returns just a string, then it's assumed to be text/plain and it's wrapped in an array to conform to Rack:  `[status_code, {headers}, [body]]`.  If it returns an array, then it's passed back to Rack directly.  The `Rack::Response` object is only used if the method returns `nil`.  So if you return a string, setting headers in the response object doesn't have an effect.

So if you want to return HTML, you can do one of these:

```
# An array:
get {
  [200,
   # Rack started requiring header names to be lower-case at some point:
   {'content-type' => 'text/html'},
   ['<html><body><h1>Hello, <em>World!</em></h1></body></html>']]
}

# Using the Rack::Response:
get {
  response.headers['content-type'] = 'text/html'
  response.body << '<html><body><h1>Hello, <strong>World!</strong></h1></body></html>'
  nil
}

# Using the Rack::Response as an array:
get {
  response.headers['content-type'] = 'text/html'
  response.body << '<html><body><h1><blink><marquee>Hello, World!</marquee></blink></h1></body></html>'
  response.to_a
}
```

I tried to find where this was documented so that I could point you to it, but it was not documented anywhere.  I've added an explanation to the README and an example to doc/examples/return.ru.  There have been a handful of fixes, so I'll probably do a release if I run this version for a while and nothing blows up.
